groups:
  # Должны быть определены все группы, что есть на сервере
  # Если группа не определена - её вес будет 999

  # Регистр групп обязан быть таким же, как и в системе привилегий
  default:
    # Вес - обязательное поле каждой группы. Это приоритет для всех наказаний
    weight: 1

    # Лимиты, необязательный параметр
    limits:
      # Лимит на временный бан (В миллисекундах)
      ban: 100

      # Лимит на временный мут (В миллисекундах)
      mute: 120

  admin:
    weight: 10

    # Секция limits не определена -> у админа нет никаких ограничений
    # Также можно не указывать в ней лимит мута/бана

    # P.S. На админские баны и муты лимиты не действуют

messages:
  # Название консоли (Используется при выдачи наказаний от имени консоли)
  consoleName: "&cКОНСОЛЬ"

  # Заполнители для каждого сообщения/гуи:
  # {name} - кого кикнули/забанили, {admin} - кто кикнул/забанил
  # {reason} - причина, {time} - для указания времени наказания

  # Кик
  kick-message: "&bИгрок &c{player} &bбыл кикнут администратором &c{admin}. &bПо причине &c{reason}"
  kick-gui: "&bВы были кикнуты игроком &c{admin}\n&bПо причине &c{reason}"

  # Бан
  ban-gui: "&bВы были забанены игроком &c&l{admin}\n&bПо причине &c&l{reason}.\n&bНа срок: &c{time}"
  ban-message: "&bИгрок &c{player} &bбыл забанен администратором &c{admin}. &bСрок действия: &c{time}. &bПо причине &c{reason}"

  #Сообщение о разбане
  unban-message: "&bАдминистратор &c{admin} &bразбанил игрока &c{player} &bпо причине &c{reason}"

  #Мут
  mute-local: "&cВы были замучены!"
  mute-message: "&bИгрок &e{player} &bбыл замучен администратором &c{admin}. &bСрок действия: &d{time}. &bПо причине &c&l{reason}"
  chat-cancel: "&c&lВы были замучены, писать в чат запрещено! (Мут от &c{admin}&c&l)"

  # Сообщение о размуте
  unmute-message: "&bАдминистратор &c{admin} &bразмутил игрока &c{player} &bпо причине &c{reason}"

  # Админ бан
  admin-ban-gui: "&bВы были забанены игроком &c&l{admin}\n&bПо причине &c&l{reason}.\n&bНа срок: &c{time}"
  admin-ban-message: "&bИгрок &c{player} &bбыл забанен администратором &c{admin}. &bСрок действия: &c{time}. &bПо причине &c{reason}"

  admin-unban-message: "&bАдминистратор &c{admin} &bразбанил игрока &c{player} &bпо причине &c{reason}"

  # Админский мут
  admin-mute-local: "&cВы были замучены!"
  admin-mute-message: "&bИгрок &e{player} &bбыл замучен администратором &c{admin}. &bСрок действия: &d{time}. &bПо причине &c&l{reason}"

  admin-unmute-message: "&bАдминистратор &c{admin} &bразмутил игрока &c{player} &bпо причине &c{reason}"


  # Формат отображения наказания в списках
  punishemnt-format: "&7{index}. &b{player} {type} &c{admin}. &eПричина: &c&l{reason}  &b(Время: {time})"